[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Rewrite rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
