services:
  - type: web
    name: fantaschedine-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://jeckoitaly_db_user:KABiHZoCLh2VgJZG@cluster0.zkxgypk.mongodb.net/fantaschedine
      - key: JWT_SECRET
        value: fantaschedine_secret_key_2024
